# Generated by Django 2.1.3 on 2019-05-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_debt_splitbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitbill',
            name='admin_user',
        ),
    ]
