# Generated by Django 2.1.3 on 2019-05-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_remove_splitbill_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplitBill',
        ),
    ]
