# Generated by Django 2.1.3 on 2019-05-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='salary',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
